---
apiVersion: v1
kind: Secret
metadata:
  name: mysecrets
data:
  password1.txt: cGFzc3dvcmQxMjM=  # output from:  echo -n 'password123' | base64
  password2.txt: cGFzc3dvcmR4eXo=  # output from:  echo -n 'passwordxyz' | base64