---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: codingbee-object-quota
  namespace: codingbee
spec:
  hard:
    pods: 2
    secrets: 1
    services.nodeports: 0
    services.loadbalancers: 0


    