---
apiVersion: v1
kind: Pod
metadata:
  name: pod-httpd-provider
  labels:
    component: apache_webserver
spec: 
  containers:
    - name: cntr-httpd
      image: httpd
      
      ports:
        - containerPort: 80