apiVersion: v1
kind: Service
metadata:
  name: svc-nodeport-apache-webserver
  namespace: codingbee
spec:
  type: NodePort
  ports:
    - port: 3050

      targetPort: 80
      nodePort: 31000
  selector:
    component: apache_webserver