---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: codingbee-compute-quota
  namespace: codingbee
spec:
  hard:
    requests.cpu: 1
    limits.cpu: 2 
    requests.memory: 1Gi
    limits.memory: 2Gi


    